let data = [
  {
    "id": 1,
    "name": "Dilwale Dulhania Le Jayenge",
    "slug": "dilwale-dulhania-le-jayenge",
    "year": 1995,
    "plot": "A love story of Raj and Simran, with a special role of their families who are against their wishes.",
    "genre": ["Romance", "Drama", "Comedy"],
    "youtube_trailer": "https://www.youtube.com/watch?v=c25GKl5VNeY",
    "actors": ["Shah Rukh Khan", "Kajol", "Amrita Singh"],
    "awards": ["Filmfare Award - Best Film", "National Award - Best Film"],
    "imdb_rating": 8.1,
    "directors": ["Aditya Chopra"],
    "box_office_collection": "₹102 crores",
    "poster": "https://m.media-amazon.com/images/I/81RTfJFpnyL._AC_UF894,1000_QL80_.jpg"
  },
  {
    "id": 2,
    "name": "Gadar: Ek Prem Katha",
    "slug": "gadar-ek-prem-katha",
    "year": 2001,
    "plot": "The story of a Hindustani Sikh family who has to go to Pakistan during the partition.",
    "genre": ["Action", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=JADZLy5HEPo",
    "actors": ["Sunny Deol", "Amisha Patel"],
    "awards": ["Filmfare Award - Best Film", "Filmfare Award - Best Direction"],
    "imdb_rating": 7.2,
    "directors": ["Anil Sharma"],
    "box_office_collection": "₹133 crores",
    "poster": "https://intv-cms-images.s3.amazonaws.com/2023/06/gadar-ek-prem-katha-1686247278.jpg"
  },
  {
    "id": 3,
    "name": "3 Idiots",
    "slug": "3-idiots",
    "year": 2009,
    "plot": "A story of three engineering students and their adventures.",
    "genre": ["Comedy", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=DKzBmRRdPXo",
    "actors": ["Aamir Khan", "Kareena Kapoor", "R. Madhavan"],
    "awards": ["Filmfare Award - Best Film", "National Award - Best Popular Film Providing Wholesome Entertainment"],
    "imdb_rating": 8.4,
    "directors": ["Rajkumar Hirani"],
    "box_office_collection": "₹460 crores",
    "poster": "https://rukminim2.flixcart.com/image/850/1000/jthjki80/poster/r/y/b/small-boly3-dpostf-3-idiots-aamir-khan-bollywood-hindi-small-original-imafet9zgyuueswb.jpeg?q=90&crop=false"
  },
  {
    "id": 4,
    "name": "Lagaan",
    "slug": "lagaan",
    "year": 2001,
    "plot": "A group of villagers challenge the British to a cricket match to avoid paying high taxes.",
    "genre": ["Drama", "Sport"],
    "youtube_trailer": "https://www.youtube.com/watch?v=oSIGQ0YkFxs",
    "actors": ["Aamir Khan", "Gracy Singh"],
    "awards": ["Filmfare Award - Best Film", "National Award - Best Popular Film Providing Wholesome Entertainment"],
    "imdb_rating": 8.1,
    "directors": ["Ashutosh Gowariker"],
    "box_office_collection": "₹65 crores",
    "poster": "https://www.researchgate.com/publication/311669009/figure/fig2/AS:494797813420032@1494980399432/Lagaan-Once-Upon-a-Time-In-India-Movie-Poster-Dir-Ashutosh-Gowariker-2001-Aamir.png"
  },
  {
    "id": 5,
    "name": "Sholay",
    "slug": "sholay",
    "year": 1975,
    "plot": "Two criminals are hired to capture a ruthless dacoit.",
    "genre": ["Action", "Adventure", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=zzTUvWfvlBg",
    "actors": ["Dharmendra", "Amitabh Bachchan", "Hema Malini"],
    "awards": ["Filmfare Award - Best Film", "National Award - Best Popular Film Providing Wholesome Entertainment"],
    "imdb_rating": 8.2,
    "directors": ["Ramesh Sippy"],
    "box_office_collection": "Unknown",
    "poster": "https://rukminim1.flixcart.com/image/300/300/xif0q/poster/6/t/t/small-spos11192-poster-sholay-movie-amitabh-dharmendra-poster-original-imaghyv5xbzcndwt.jpeg"
  },
  {
    "id": 6,
    "name": "PK",
    "slug": "pk",
    "year": 2014,
    "plot": "An alien comes to Earth on a research mission but loses his remote to go back to his planet.",
    "genre": ["Comedy", "Drama", "Fantasy"],
    "youtube_trailer": "https://www.youtube.com/watch?v=SOXWc32k4zA",
    "actors": ["Aamir Khan", "Anushka Sharma"],
    "awards": ["Filmfare Award - Best Film"],
    "imdb_rating": 8.2,
    "directors": ["Rajkumar Hirani"],
    "box_office_collection": "₹832 crores",
    "poster": "https://i.ytimg.com/vi/v38ezoaqB3E/sddefault.jpg"
  },
  {
    "id": 7,
    "name": "Baahubali: The Beginning",
    "slug": "baahubali-the-beginning",
    "year": 2015,
    "plot": "The story of the kingdom of Mahishmati and the revenge of a son.",
    "genre": ["Action", "Adventure", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=sOEg_YZQsTI",
    "actors": ["Prabhas", "Rana Daggubati", "Anushka Shetty"],
    "awards": ["National Award - Best Feature Film"],
    "imdb_rating": 8.1,
    "directors": ["S.S. Rajamouli"],
    "box_office_collection": "₹650 crores",
    "poster": "https://lh3.googleusercontent.com/proxy/hrtyVNzPmU2SxZD7FPK5n7vW8f3LpxSWsJcfLbYo3UzvCkJAsg2sXhEb1HtowPwqyzqfA3lKveYa1Drm6cdtmo1rG13BJO3HZXo6o9RQZXN1l8MUXcPvhLCV9NYK4c_H3xugJ1_VM8g"
  },
  {
    "id": 8,
    "name": "Baahubali 2: The Conclusion",
    "slug": "baahubali-2-the-conclusion",
    "year": 2017,
    "plot": "The continuation of Baahubali's journey to find the truth about his heritage and love.",
    "genre": ["Action", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=G62HrubdD6o",
    "actors": ["Prabhas", "Rana Daggubati", "Anushka Shetty"],
    "awards": ["National Award - Best Feature Film"],
    "imdb_rating": 8.3,
    "directors": ["S.S. Rajamouli"],
    "box_office_collection": "₹1,810 crores",
    "poster": "https://rukminim2.flixcart.com/image/850/1000/l2hwwi80/poster/z/0/b/small-poster-bahubali-2-the-conclusion-3-sl073-wall-poster-13x19-original-imaezywyfefe7k7u.jpeg?q=90&crop=false"
  },
  {
    "id": 9,
    "name": "Padmaavat",
    "slug": "padmaavat",
    "year": 2018,
    "plot": "The story of the legendary queen Padmavati and her husband Maharawal Ratan Singh.",
    "genre": ["Drama", "History"],
    "youtube_trailer": "https://www.youtube.com/watch?v=X_5_BLt76c0",
    "actors": ["Deepika Padukone", "Shahid Kapoor", "Ranveer Singh"],
    "awards": ["Filmfare Award - Best Actor (Critics) - Ranveer Singh"],
    "imdb_rating": 7.0,
    "directors": ["Sanjay Leela Bhansali"],
    "box_office_collection": "₹585 crores",
    "poster": "https://static.toiimg.com/photo/65870743.cms"
  },
  {
    "id": 10,
    "name": "Gully Boy",
    "slug": "gully-boy",
    "year": 2019,
    "plot": "A coming-of-age story of a street rapper from Mumbai.",
    "genre": ["Drama", "Music"],
    "youtube_trailer": "https://www.youtube.com/watch?v=JfbxcD6biOk",
    "actors": ["Ranveer Singh", "Alia Bhatt"],
    "awards": ["Filmfare Award - Best Film"],
    "imdb_rating": 8.0,
    "directors": ["Zoya Akhtar"],
    "box_office_collection": "₹238 crores",
    "poster": "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2019/01/01/772781-000-gully-boy.jpg"
  },
  {
    "id": 11,
    "name": "Bajrangi Bhaijaan",
    "slug": "bajrangi-bhaijaan",
    "year": 2015,
    "plot": "A man with a magnanimous heart helps a mute Pakistani girl return to her homeland to reunite with her family.",
    "genre": ["Drama", "Comedy"],
    "youtube_trailer": "https://www.youtube.com/watch?v=4nwAra0mz_Q",
    "actors": ["Salman Khan", "Harshaali Malhotra", "Kareena Kapoor"],
    "awards": ["National Award - Best Popular Film Providing Wholesome Entertainment"],
    "imdb_rating": 8.0,
    "directors": ["Kabir Khan"],
    "box_office_collection": "₹969 crores",
    "poster": "https://static.toiimg.com/thumb/msid-48098885,width-1070,height-580,imgsize-230910,resizemode-75,overlay-toi_sw,pt-32,y_pad-40/photo.jpg"
  },
  {
    "id": 12,
    "name": "Andhadhun",
    "slug": "andhadhun",
    "year": 2018,
    "plot": "A series of mysterious events take place in the life of a blind pianist.",
    "genre": ["Thriller", "Mystery"],
    "youtube_trailer": "https://www.youtube.com/watch?v=2iVYI99VGaw",
    "actors": ["Ayushmann Khurrana", "Tabu", "Radhika Apte"],
    "awards": ["Filmfare Award - Best Actor - Ayushmann Khurrana", "National Award - Best Hindi Film"],
    "imdb_rating": 8.3,
    "directors": ["Sriram Raghavan"],
    "box_office_collection": "₹456 crores",
    "poster": "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2018/09/fgg-1536050018.jpg"
  },
  {
    "id": 13,
    "name": "Queen",
    "slug": "queen",
    "year": 2013,
    "plot": "A Delhi girl from a traditional family sets out on a solo honeymoon trip after her marriage gets canceled.",
    "genre": ["Comedy", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=KGC6vl3lzf0",
    "actors": ["Kangana Ranaut", "Rajkummar Rao"],
    "awards": ["National Award - Best Feature Film in Hindi"],
    "imdb_rating": 8.2,
    "directors": ["Vikas Bahl"],
    "box_office_collection": "₹108 crores",
    "poster": "https://www.michigandaily.com/wp-content/uploads/2018/10/unnamed-16.jpg"
  },
  {
    "id": 14,
    "name": "Dangal",
    "slug": "dangal",
    "year": 2016,
    "plot": "The story of the Phogat sisters who were trained by their father to become world-class wrestlers.",
    "genre": ["Biography", "Drama", "Sport"],
    "youtube_trailer": "https://www.youtube.com/watch?v=x_7YlGv9u1g",
    "actors": ["Aamir Khan", "Sakshi Tanwar"],
    "awards": ["Filmfare Award - Best Film", "National Award - Best Feature Film"],
    "imdb_rating": 8.4,
    "directors": ["Nitesh Tiwari"],
    "box_office_collection": "₹2,024 crores",
    "poster": "https://s1.dmcdn.net/v/GO28E1NUcAII2MREF/x1080"
  },
  {
    "id": 15,
    "name": "Article 15",
    "slug": "article-15",
    "year": 2019,
    "plot": "A police officer investigates the disappearance of three girls in a village.",
    "genre": ["Crime", "Drama", "Thriller"],
    "youtube_trailer": "https://www.youtube.com/watch?v=HKOJY0cU63E",
    "actors": ["Ayushmann Khurrana", "Isha Talwar", "Sayani Gupta"],
    "awards": ["Filmfare Award - Critics Award for Best Actor"],
    "imdb_rating": 8.2,
    "directors": ["Anubhav Sinha"],
    "box_office_collection": "₹92 crores",
    "poster": "https://i0.wp.com/velivada.com/wp-content/uploads/2020/09/article-15-review.jpg?fit=1000%2C563&ssl=1"
  },
  {
    "id": 16,
    "name": "Uri: The Surgical Strike",
    "slug": "uri-the-surgical-strike",
    "year": 2019,
    "plot": "The story of the 2016 surgical strikes conducted by the Indian Army in retaliation to the Uri attack.",
    "genre": ["Action", "Drama", "War"],
    "youtube_trailer": "https://www.youtube.com/watch?v=VVY3do673Zc",
    "actors": ["Vicky Kaushal", "Paresh Rawal", "Yami Gautam"],
    "awards": ["National Award - Best Director", "National Award - Best Actor (Vicky Kaushal)"],
    "imdb_rating": 8.3,
    "directors": ["Aditya Dhar"],
    "box_office_collection": "₹342 crores",
    "poster": "https://www.clockworkfilm.com/meta-content/uploads/2019/01/uri-main-img-1200x675.jpg"
  },
  {
    "id": 17,
    "name": "Munna Bhai M.B.B.S.",
    "slug": "munna-bhai-mbbs",
    "year": 2003,
    "plot": "A gangster sets out to fulfill his father's dream of becoming a doctor.",
    "genre": ["Comedy", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=6lCGvu-hwX4",
    "actors": ["Sanjay Dutt", "Arshad Warsi", "Boman Irani"],
    "awards": ["Filmfare Award - Best Dialogue", "Filmfare Award - Best Comedian"],
    "imdb_rating": 8.1,
    "directors": ["Rajkumar Hirani"],
    "box_office_collection": "₹38 crores",
    "poster": "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2020/12/pjimage-48-1606906136.jpg"
  },
  {
    "id": 18,
    "name": "Kabir Singh",
    "slug": "kabir-singh",
    "year": 2019,
    "plot": "A brilliant yet impulsive young surgeon falls into a self-destructive pattern after his girlfriend's family doesn't approve of their relationship.",
    "genre": ["Drama", "Romance"],
    "youtube_trailer": "https://www.youtube.com/watch?v=RiANSSgCuJk",
    "actors": ["Shahid Kapoor", "Kiara Advani"],
    "awards": ["Filmfare Award - Best Actor - Shahid Kapoor"],
    "imdb_rating": 7.1,
    "directors": ["Sandeep Reddy Vanga"],
    "box_office_collection": "₹379 crores",
    "poster": "https://akm-img-a-in.tosshub.com/businesstoday/images/story/201906/kabir_singh_poster2_660_062119041041.jpg"
  },
  {
    "id": 19,
    "name": "Om Shanti Om",
    "slug": "om-shanti-om",
    "year": 2007,
    "plot": "In the 1970s, a junior artist falls in love with a superstar and helps him seek revenge against his enemies.",
    "genre": ["Action", "Comedy", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=9oeGoQGt7Ao",
    "actors": ["Shah Rukh Khan", "Deepika Padukone"],
    "awards": ["Filmfare Award - Best Film", "Filmfare Award - Best Male Debut (Farah Khan)"],
    "imdb_rating": 6.7,
    "directors": ["Farah Khan"],
    "box_office_collection": "₹150 crores",
    "poster": "https://c8.alamy.com/comp/B84ECH/om-shanti-om-oso-year-2007-india-affiche-poster-director-farah-khan-B84ECH.jpg"
  },
  {
    "id": 20,
    "name": "Dabangg",
    "slug": "dabangg",
    "year": 2010,
    "plot": "A corrupt police officer faces challenges from his family and the society.",
    "genre": ["Action", "Comedy", "Drama"],
    "youtube_trailer": "https://www.youtube.com/watch?v=v5v3JA2b9vY",
    "actors": ["Salman Khan", "Sonakshi Sinha"],
    "awards": ["Filmfare Award - Best Female Debut (Sonakshi Sinha)"],
    "imdb_rating": 6.3,
    "directors": ["Abhinav Kashyap"],
    "box_office_collection": "₹215 crores",
    "poster": "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2019/12/dabangg-3-1576763967.jpg"
  }
]


export default data;
